local pets_rarity = {
  ["Common"] = {
    ["Bunny"] = true,
    ["Dog"] = true,
    ["Golden Lab"] = true,
    ["Hamster"] = true,
  },
  ["Uncommon"] = {
    ["Black Bunny"] = true,
    ["Chicken"] = true,
    ["Cat"] = true,
    ["Deer"] = true,
  },
  ["Rare"] = {
    ["Orange Tabby"] = true,
    ["Spotted Deer"] = true,
    ["Pig"] = true,
    ["Rooster"] = true,
    ["Monkey"] = true,
    ["Hedgehog"] = true,
    ["Flamingo"] = true,
    ["Sea Turtle"] = true,
    ["Toucan"] = true,
    ["Wasp"] = true,
    ["Honey Bee"] = true,
    ["Cooked Owl"] = true,
  },
  ["Legendary"] = {
    ["Cow"] = true,
    ["Silver Monkey"] = true,
    ["Tarantula Hawk"] = true,
    ["Mole"] = true,
    ["Seal"] = true,
    ["Orangutan"] = true,
    ["Peacock"] = true,
    ["Ostrich"] = true,
    ["Axolotl"] = true,
    ["Triceratops"] = true,
    ["Stegosaurus"] = true,
    ["Scarlet Macaw"] = true,
    ["Polar Bear"] = true,
    ["Sea Otter"] = true,
    ["Turtle"] = true,
    ["Raptor"] = true,
    ["Pterodactyl"] = true,
    ["Moth"] = true,
  },
  ["Mythical"] = {
    ["Snail"] = true,
    ["Giant Ant"] = true,
    ["Caterpillar"] = true,
    ["Praying Mantis"] = true,
    ["Butterfly"] = true,
    ["Echo Frog"] = true,
    ["Frog"] = true,
    ["Hyacinth Macaw"] = true,
    ["Petal Bee"] = true,
    ["Bear Bee"] = true,
    ["Brontosaurus"] = true,
    ["Blood Bunny"] = true,
    ["Blood Deer"] = true,
    ["Blood Macaw"] = true,
  },
  ["Divine"] = {
    ["Dragonfly"] = true,
    ["Queen Bee"] = true,
    ["Raccoon"] = true,
    ["Night Owl"] = true,
    ["Fennec Fox"] = true,
    ["Disco Bee"] = true,
    ["Mimic Octopus"] = true,
    ["T-Rex"] = true,
  },
}

return pets_rarity
